---
# Pick a UNIQUE team name. This is important because it will be used in the
# names of things, so take some time to come up with a good one.
# Don't take BuffaloBill, because that's mine.
team_name: zombie-slothpops2

scoring:
  # In your gameday team dashboard, there will be an API token that looks like
  # this. To get points you MUST CHANGE THIS
  api_token: "4eed690923"
  # The scoring URL should not need to be changed
  url: "https://dashboard.cash4code.net/score"

iam_profile: "arn:aws:iam::176762829186:instance-profile/qls-625183-5d519d24957d585b-PlayerInstanceProfile-LIAXD2YPMNJ1"
iam_exec_arn: "arn:aws:iam::176762829186:role/qls-625183-5d519d24957d585b-PlayerRole-UGLLLXR8DY6J"

s3_deployment_package: unicorn

# The AWS CLI profile you'll be using for the game
# Ansible uses these credentials as well, so follow the instructions here:
# http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-set-up.html
# And use the `aws configure` command to set up a profile that connects to your
# gameday AWS account

# Go to the EC2 console and make an SSH keypair, then put its name here
ssh_key_name: zombie-slothpops

# The name for the EC2 launch configuration and autoscaling group to be created. For more about this
# resource, see `server.yml`
launch_config: ZombieSlothpopsLC002
autoscaling_group: ZombieSlothpops

# the AWS region to use, for the gameday please use eu-central-1
region: eu-central-1
